steps:
- name: gcr.io/kaniko-project/executor:latest
  id: perciai
  args: [--destination=gcr.io/$PROJECT_ID/perciai:$COMMIT_SHA, --cache=true, --dockerfile=Dockerfile, --context=.]
  waitFor: [-]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'services', 'update', 'perciappcloudrun', '--image', 'gcr.io/$PROJECT_ID/perciai:$COMMIT_SHA', '--region', 'us-central1', '--platform', 'managed']
timeout: "600s"
