steps:
- name: gcr.io/kaniko-project/executor:latest
  id: perciai
  args: [--destination=gcr.io/$PROJECT_ID/perciai:$COMMIT_SHA, --cache=false, --dockerfile=Dockerfile, --context=.]
  waitFor: [-]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'services', 'update', 'perciappcloudrun', '--image', 'gcr.io/$PROJECT_ID/perciai:$COMMIT_SHA', '--region', 'us-central1', '--platform', 'managed']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'services', 'update', 'perciappprocessor', '--image', 'gcr.io/$PROJECT_ID/perciai:$COMMIT_SHA', '--region', 'us-central1', '--platform', 'managed']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gsutil','cp', '-r', 'gs://perciapp-processor/models', 'perciapp/models']
timeout: "2400s"
