Subcategories = {
    'clothing' : [('tops', 'Tops'), ('bottoms', 'Bottoms'),('t-shirts & singlets', 'T-shirts & Singlets'),
                ('shirts & polos', 'Shirts & Polos'), ('dresses', 'Dresses'), ('skirts', 'Skirts'),
                ('swimwear', 'Swimwear'), ('pants', 'Pants'), ('jeans', 'Jeans'), ('shorts', 'Shorts'),
                ('sweats & hoodies', 'Sweats & Hoodies'), ('coats & jackets', 'Coats & Jackets'),
                ('suits & blazers', 'Suits & Blazers'), ('jumpers & cardigans', 'Sweaters'),
                ('sleepwear', 'Sleepwear'), ('underwear & socks', 'Underwear & Socks'), ('base layers', 'Base Layers'),
                ('lingerie', 'Lingerie'), ('jumpsuits & playsuits', 'Jumpsuits & Playsuits'), ('onesies', 'Onesies'),
                ('tights', 'Tights')],
    'shoes' : [('ankle boots', 'Ankle Boots'),
        ('dress shoes', 'Dress Shoes'),
        ('boots', 'Boots'),
        ('flats', 'Flats'),
        ('heels', 'Heels'),
        ('sneakers', 'Sneakers'),
        ('sandals', 'Sandals'),
        ('performance shoes', 'Performance Shoes'),
        ('wedges', 'Wedges'),
        ('casual shoes', 'Casual Shoes'),
        ('slippers', 'Slippers')],
    'accessories' : [('sunglasses', 'Sunglasses'),
        ('bags', 'Bags'),
        ('jewellery', 'Jewellery'),
        ('ties & cufflinks', 'Ties & Cufflinks'),
        ('watches', 'Watches'),
        ('scarves & gloves', 'Scarves & Gloves'),
        ('headwear', 'Headwear'),
        ('wallets', 'Wallets'),
        ('belts', 'Belts')]
}